#!/usr/bin/env python3
"""
Manually curated list of Romanian affective states for ASI benchmark.

These are words that describe HOW SOMEONE FEELS - their emotional or mental state.
Curated from RoEmoLex V3 by reviewing each entry.

Criteria for inclusion:
- Can be used with "mă simt [X]" (I feel X)
- Or "sunt [X]" (I am X) to describe an emotional state
- Or "am [X]" / "simt [X]" for emotion nouns

Excluded:
- Professions/roles (elev, profesor, doctor)
- Objects/things (masă, carte, bani)
- Events (accident, concert)
- Places (aeroport, spital)
- Animals/creatures
- Abstract non-emotional concepts
"""

# Affective state ADJECTIVES - words you can use with "mă simt [X]" or "sunt [X]"
AFFECTIVE_ADJECTIVES = {
    # Joy / Happiness
    "fericit": ["joy"],
    "fericită": ["joy"],
    "bucuros": ["joy"],
    "bucuroasă": ["joy"],
    "vesel": ["joy"],
    "veselă": ["joy"],
    "încântat": ["joy"],
    "încântată": ["joy"],
    "entuziasmat": ["joy", "anticipation"],
    "entuziasmată": ["joy", "anticipation"],
    "mulțumit": ["joy"],
    "mulțumită": ["joy"],
    "satisfăcut": ["joy"],
    "împlinit": ["joy"],
    "împlinită": ["joy"],
    "extaziat": ["joy"],
    "extaziată": ["joy"],
    "amuzat": ["joy"],
    "amuzată": ["joy"],
    "binedispus": ["joy"],
    "binedispusă": ["joy"],
    "radiind": ["joy"],
    "înviorat": ["joy"],
    "înviată": ["joy"],
    "voios": ["joy"],
    "voioasă": ["joy"],
    "jovial": ["joy"],
    "exuberant": ["joy"],
    "exuberantă": ["joy"],
    "euforic": ["joy"],
    "euforică": ["joy"],
    "optimist": ["joy", "anticipation"],
    "optimistă": ["joy", "anticipation"],
    "mândru": ["joy"],
    "mândră": ["joy"],
    "recunoscător": ["joy", "trust"],
    "recunoscătoare": ["joy", "trust"],
    "plin de viață": ["joy"],

    # Sadness
    "trist": ["sadness"],
    "tristă": ["sadness"],
    "nefericit": ["sadness"],
    "nefericită": ["sadness"],
    "deprimat": ["sadness"],
    "deprimată": ["sadness"],
    "abătut": ["sadness"],
    "abătută": ["sadness"],
    "dezamăgit": ["sadness"],
    "dezamăgită": ["sadness"],
    "mâhnit": ["sadness"],
    "mâhnită": ["sadness"],
    "îndurerat": ["sadness"],
    "îndurerată": ["sadness"],
    "demoralizat": ["sadness"],
    "demoralizată": ["sadness"],
    "descurajat": ["sadness"],
    "descurajată": ["sadness"],
    "melancolic": ["sadness"],
    "melancolică": ["sadness"],
    "amărât": ["sadness"],
    "amărâtă": ["sadness"],
    "posomorât": ["sadness"],
    "posomorâtă": ["sadness"],
    "abătut": ["sadness"],
    "singur": ["sadness"],
    "singură": ["sadness"],
    "însingurat": ["sadness"],
    "însingurată": ["sadness"],
    "pustiu": ["sadness"],
    "gol": ["sadness"],
    "goală": ["sadness"],
    "neconsolat": ["sadness"],
    "neconsolată": ["sadness"],
    "disperat": ["sadness", "fear"],
    "disperată": ["sadness", "fear"],
    "pesimist": ["sadness"],
    "pesimistă": ["sadness"],
    "mohorât": ["sadness"],
    "mohorâtă": ["sadness"],
    "plictisit": ["sadness"],
    "plictisită": ["sadness"],
    "apatic": ["sadness"],
    "apatică": ["sadness"],
    "obosit": ["sadness"],
    "obosită": ["sadness"],
    "epuizat": ["sadness"],
    "epuizată": ["sadness"],
    "istovit": ["sadness"],
    "istovită": ["sadness"],
    "sleit": ["sadness"],
    "sleită": ["sadness"],
    "rănit": ["sadness"],
    "rănită": ["sadness"],
    "zdrobit": ["sadness"],
    "zdrobită": ["sadness"],
    "distrus": ["sadness"],
    "distrusă": ["sadness"],
    "devastat": ["sadness"],
    "devastată": ["sadness"],
    "nenorocit": ["sadness"],
    "nenorocită": ["sadness"],
    "năpăstuit": ["sadness"],
    "năpăstuită": ["sadness"],

    # Fear / Anxiety
    "speriat": ["fear"],
    "speriată": ["fear"],
    "înfricoșat": ["fear"],
    "înfricoșată": ["fear"],
    "îngrozit": ["fear"],
    "îngrozită": ["fear"],
    "îngrijorat": ["fear"],
    "îngrijorată": ["fear"],
    "anxios": ["fear"],
    "anxioasă": ["fear"],
    "neliniștit": ["fear"],
    "neliniștită": ["fear"],
    "agitat": ["fear", "anticipation"],
    "agitată": ["fear", "anticipation"],
    "panicat": ["fear"],
    "panicată": ["fear"],
    "alarmat": ["fear"],
    "alarmată": ["fear"],
    "temător": ["fear"],
    "temătoare": ["fear"],
    "fricos": ["fear"],
    "fricoasă": ["fear"],
    "nervos": ["fear", "anger"],
    "nervoasă": ["fear", "anger"],
    "stresat": ["fear"],
    "stresată": ["fear"],
    "tensionat": ["fear"],
    "tensionată": ["fear"],
    "încordat": ["fear"],
    "încordată": ["fear"],
    "nesigur": ["fear"],
    "nesigură": ["fear"],
    "confuz": ["fear", "surprise"],
    "confuză": ["fear", "surprise"],
    "dezorientat": ["fear"],
    "dezorientată": ["fear"],
    "tulburat": ["fear"],
    "tulburată": ["fear"],
    "perturbat": ["fear"],
    "perturbată": ["fear"],
    "înnebunit": ["fear"],
    "înnebunită": ["fear"],
    "paranoid": ["fear"],
    "paranoică": ["fear"],
    "suspicios": ["fear"],
    "suspicioasă": ["fear"],
    "precaut": ["fear"],
    "precaută": ["fear"],
    "circumspect": ["fear"],
    "circumspectă": ["fear"],
    "inhibat": ["fear"],
    "inhibată": ["fear"],
    "timid": ["fear"],
    "timidă": ["fear"],
    "sfios": ["fear"],
    "sfioasă": ["fear"],
    "intimidat": ["fear"],
    "intimidată": ["fear"],
    "terorizat": ["fear"],
    "terorizată": ["fear"],
    "traumatizat": ["fear", "sadness"],
    "traumatizată": ["fear", "sadness"],

    # Anger
    "furios": ["anger"],
    "furioasă": ["anger"],
    "supărat": ["anger"],
    "supărată": ["anger"],
    "enervat": ["anger"],
    "enervată": ["anger"],
    "iritat": ["anger"],
    "iritată": ["anger"],
    "înfuriat": ["anger"],
    "înfuriată": ["anger"],
    "mânios": ["anger"],
    "mânioasă": ["anger"],
    "indignat": ["anger"],
    "indignată": ["anger"],
    "revoltat": ["anger"],
    "revoltată": ["anger"],
    "exasperat": ["anger"],
    "exasperată": ["anger"],
    "frustrat": ["anger"],
    "frustrată": ["anger"],
    "agasat": ["anger"],
    "agasată": ["anger"],
    "nemulțumit": ["anger", "sadness"],
    "nemulțumită": ["anger", "sadness"],
    "dezgustat": ["anger", "disgust"],
    "dezgustată": ["anger", "disgust"],
    "scârbit": ["anger", "disgust"],
    "scârbită": ["anger", "disgust"],
    "ofensat": ["anger"],
    "ofensată": ["anger"],
    "jignit": ["anger"],
    "jignită": ["anger"],
    "ranchiunos": ["anger"],
    "ranchiunoasă": ["anger"],
    "ostil": ["anger"],
    "ostilă": ["anger"],
    "beligerant": ["anger"],
    "beligerantă": ["anger"],
    "agresiv": ["anger"],
    "agresivă": ["anger"],
    "violent": ["anger"],
    "violentă": ["anger"],
    "turbat": ["anger"],
    "turbată": ["anger"],
    "posac": ["anger"],
    "posacă": ["anger"],
    "ursuz": ["anger"],
    "ursuză": ["anger"],
    "morocănos": ["anger"],
    "morocănoasă": ["anger"],
    "bosumflat": ["anger"],
    "bosumflată": ["anger"],
    "arțăgos": ["anger"],
    "arțăgoasă": ["anger"],
    "certăreț": ["anger"],
    "certăreață": ["anger"],
    "gelos": ["anger", "sadness"],
    "geloasă": ["anger", "sadness"],
    "invidios": ["anger", "sadness"],
    "invidioasă": ["anger", "sadness"],

    # Disgust
    "dezgustat": ["disgust"],
    "dezgustată": ["disgust"],
    "scârbit": ["disgust"],
    "scârbită": ["disgust"],
    "grețos": ["disgust"],
    "gretoasă": ["disgust"],
    "oripilat": ["disgust"],
    "oripilată": ["disgust"],
    "îngrozit": ["disgust", "fear"],
    "îngrozită": ["disgust", "fear"],
    "respins": ["disgust"],
    "respinsă": ["disgust"],
    "astomacat": ["disgust"],
    "astomacată": ["disgust"],

    # Surprise
    "surprins": ["surprise"],
    "surprinsă": ["surprise"],
    "uimit": ["surprise"],
    "uimită": ["surprise"],
    "uluit": ["surprise"],
    "uluită": ["surprise"],
    "șocat": ["surprise"],
    "șocată": ["surprise"],
    "năucit": ["surprise"],
    "năucită": ["surprise"],
    "stupefiat": ["surprise"],
    "stupefiată": ["surprise"],
    "perplex": ["surprise"],
    "perplexă": ["surprise"],
    "buimăcit": ["surprise"],
    "buimăcită": ["surprise"],
    "amețit": ["surprise"],
    "amețită": ["surprise"],
    "zăpăcit": ["surprise"],
    "zăpăcită": ["surprise"],
    "consternat": ["surprise"],
    "consternată": ["surprise"],
    "descumpănit": ["surprise"],
    "descumpănită": ["surprise"],
    "nedumerit": ["surprise"],
    "nedumerită": ["surprise"],
    "contrariat": ["surprise", "anger"],
    "contrariată": ["surprise", "anger"],
    "mirat": ["surprise"],
    "mirată": ["surprise"],
    "fascinat": ["surprise", "joy"],
    "fascinată": ["surprise", "joy"],
    "captivat": ["surprise", "joy"],
    "captivată": ["surprise", "joy"],
    "impresionat": ["surprise"],
    "impresionată": ["surprise"],
    "copleșit": ["surprise"],
    "copleșită": ["surprise"],

    # Trust / Security
    "încrezător": ["trust"],
    "încrezătoare": ["trust"],
    "sigur": ["trust"],
    "sigură": ["trust"],
    "confident": ["trust"],
    "confidentă": ["trust"],
    "liniștit": ["trust"],
    "liniștită": ["trust"],
    "calm": ["trust"],
    "calmă": ["trust"],
    "relaxat": ["trust"],
    "relaxată": ["trust"],
    "senin": ["trust"],
    "senină": ["trust"],
    "împăcat": ["trust"],
    "împăcată": ["trust"],
    "echilibrat": ["trust"],
    "echilibrată": ["trust"],
    "stabil": ["trust"],
    "stabilă": ["trust"],
    "în largul meu": ["trust"],
    "confortabil": ["trust"],
    "confortabilă": ["trust"],
    "protejat": ["trust"],
    "protejată": ["trust"],
    "în siguranță": ["trust"],
    "acceptat": ["trust", "joy"],
    "acceptată": ["trust", "joy"],
    "iubit": ["trust", "joy"],
    "iubită": ["trust", "joy"],
    "apreciat": ["trust", "joy"],
    "apreciată": ["trust", "joy"],
    "respectat": ["trust"],
    "respectată": ["trust"],
    "onorat": ["trust", "joy"],
    "onorată": ["trust", "joy"],

    # Anticipation
    "nerăbdător": ["anticipation"],
    "nerăbdătoare": ["anticipation"],
    "curios": ["anticipation"],
    "curioasă": ["anticipation"],
    "intrigat": ["anticipation"],
    "intrigată": ["anticipation"],
    "entuziasmat": ["anticipation", "joy"],
    "entuziasmată": ["anticipation", "joy"],
    "încântat": ["anticipation", "joy"],
    "încântată": ["anticipation", "joy"],
    "dornic": ["anticipation"],
    "dornică": ["anticipation"],
    "ațâțat": ["anticipation"],
    "ațâțată": ["anticipation"],
    "excitat": ["anticipation", "joy"],
    "excitată": ["anticipation", "joy"],
    "așteptând": ["anticipation"],
    "plin de speranță": ["anticipation"],
    "speranțos": ["anticipation"],

    # Mixed / Other states
    "vinovat": ["sadness", "fear"],
    "vinovată": ["sadness", "fear"],
    "rușinat": ["sadness", "fear"],
    "rușinată": ["sadness", "fear"],
    "jenat": ["sadness", "fear"],
    "jenată": ["sadness", "fear"],
    "stânjenit": ["sadness", "fear"],
    "stânjenită": ["sadness", "fear"],
    "umilit": ["sadness", "anger"],
    "umilită": ["sadness", "anger"],
    "nostalgic": ["sadness", "joy"],
    "nostalgică": ["sadness", "joy"],
    "sentimental": ["sadness", "joy"],
    "sentimentală": ["sadness", "joy"],
    "emoționat": ["joy", "sadness"],
    "emoționată": ["joy", "sadness"],
    "mișcat": ["joy", "sadness"],
    "mișcată": ["joy", "sadness"],
    "înduioșat": ["joy", "sadness"],
    "înduioșată": ["joy", "sadness"],
    "sensibil": ["sadness"],
    "sensibilă": ["sadness"],
    "vulnerabil": ["fear", "sadness"],
    "vulnerabilă": ["fear", "sadness"],
    "fragil": ["fear", "sadness"],
    "fragilă": ["fear", "sadness"],
    "neajutorat": ["fear", "sadness"],
    "neajutorată": ["fear", "sadness"],
}

# Affective state NOUNS - for "simt [X]", "am [X]", "mi-e [X]" patterns
AFFECTIVE_NOUNS = {
    # Fear
    "frică": ["fear"],
    "frica": ["fear"],
    "teamă": ["fear"],
    "teama": ["fear"],
    "groază": ["fear"],
    "groaza": ["fear"],
    "spaimă": ["fear"],
    "spaima": ["fear"],
    "panică": ["fear"],
    "panica": ["fear"],
    "anxietate": ["fear"],
    "neliniște": ["fear"],
    "neliniste": ["fear"],
    "îngrijorare": ["fear"],
    "ingrijorare": ["fear"],
    "teroare": ["fear"],
    "oroare": ["fear", "disgust"],

    # Sadness
    "tristețe": ["sadness"],
    "tristete": ["sadness"],
    "durere": ["sadness"],
    "suferință": ["sadness"],
    "suferinta": ["sadness"],
    "chin": ["sadness"],
    "amărăciune": ["sadness"],
    "amaraciune": ["sadness"],
    "mâhnire": ["sadness"],
    "mahnire": ["sadness"],
    "deznădejde": ["sadness"],
    "deznadejde": ["sadness"],
    "disperare": ["sadness", "fear"],
    "melancolie": ["sadness"],
    "nostalgie": ["sadness"],
    "dor": ["sadness", "anticipation"],
    "singurătate": ["sadness"],
    "singuratate": ["sadness"],
    "gol": ["sadness"],
    "vid": ["sadness"],
    "depresie": ["sadness"],
    "apatie": ["sadness"],
    "plictiseală": ["sadness"],
    "plictiseala": ["sadness"],
    "oboseală": ["sadness"],
    "oboseala": ["sadness"],
    "epuizare": ["sadness"],

    # Joy
    "bucurie": ["joy"],
    "fericire": ["joy"],
    "plăcere": ["joy"],
    "placere": ["joy"],
    "satisfacție": ["joy"],
    "satisfactie": ["joy"],
    "mulțumire": ["joy"],
    "multumire": ["joy"],
    "entuziasm": ["joy", "anticipation"],
    "veselie": ["joy"],
    "voie": ["joy"],
    "chef": ["joy", "anticipation"],
    "extaz": ["joy"],
    "euforie": ["joy"],
    "încântare": ["joy"],
    "incantare": ["joy"],
    "deliciu": ["joy"],
    "beatitudine": ["joy"],
    "mândrie": ["joy"],
    "mandrie": ["joy"],
    "recunoștință": ["joy", "trust"],
    "recunostinta": ["joy", "trust"],
    "ușurare": ["joy", "trust"],
    "usurare": ["joy", "trust"],

    # Anger
    "furie": ["anger"],
    "mânie": ["anger"],
    "manie": ["anger"],
    "nervi": ["anger"],
    "iritare": ["anger"],
    "enervare": ["anger"],
    "exasperare": ["anger"],
    "frustrare": ["anger"],
    "indignare": ["anger"],
    "revoltă": ["anger"],
    "revolta": ["anger"],
    "ură": ["anger", "disgust"],
    "ura": ["anger", "disgust"],
    "ostilitate": ["anger"],
    "resentiment": ["anger"],
    "ranchiună": ["anger"],
    "ranchiuna": ["anger"],
    "ciudă": ["anger"],
    "ciuda": ["anger"],
    "pică": ["anger"],
    "pica": ["anger"],
    "gelozie": ["anger", "sadness"],
    "invidie": ["anger", "sadness"],

    # Disgust
    "dezgust": ["disgust"],
    "scârbă": ["disgust"],
    "scarba": ["disgust"],
    "greață": ["disgust"],
    "greata": ["disgust"],
    "repulsie": ["disgust"],
    "aversiune": ["disgust"],
    "silă": ["disgust"],
    "sila": ["disgust"],

    # Surprise
    "surpriză": ["surprise"],
    "surpriza": ["surprise"],
    "uimire": ["surprise"],
    "mirare": ["surprise"],
    "stupoare": ["surprise"],
    "perplexitate": ["surprise"],
    "șoc": ["surprise"],
    "soc": ["surprise"],
    "consternare": ["surprise"],

    # Trust
    "încredere": ["trust"],
    "incredere": ["trust"],
    "siguranță": ["trust"],
    "siguranta": ["trust"],
    "liniște": ["trust"],
    "liniste": ["trust"],
    "pace": ["trust"],
    "calm": ["trust"],
    "seninătate": ["trust"],
    "seninatate": ["trust"],
    "confort": ["trust"],
    "relaxare": ["trust"],
    "echilibru": ["trust"],

    # Anticipation
    "așteptare": ["anticipation"],
    "asteptare": ["anticipation"],
    "nerăbdare": ["anticipation"],
    "nerabdare": ["anticipation"],
    "speranță": ["anticipation", "joy"],
    "speranta": ["anticipation", "joy"],
    "curiozitate": ["anticipation"],
    "interes": ["anticipation"],

    # Mixed
    "rușine": ["sadness", "fear"],
    "rusine": ["sadness", "fear"],
    "jenă": ["sadness", "fear"],
    "jena": ["sadness", "fear"],
    "vinovăție": ["sadness", "fear"],
    "vinovatie": ["sadness", "fear"],
    "vină": ["sadness"],
    "vina": ["sadness"],
    "remușcare": ["sadness"],
    "remuscare": ["sadness"],
    "regret": ["sadness"],
    "părere de rău": ["sadness"],
    "compasiune": ["sadness", "trust"],
    "empatie": ["sadness", "trust"],
    "milă": ["sadness"],
    "mila": ["sadness"],
    "iubire": ["joy", "trust"],
    "dragoste": ["joy", "trust"],
    "afecțiune": ["joy", "trust"],
    "afectiune": ["joy", "trust"],
}

# State adverbs - for "mă simt [X]" where X is an adverb
AFFECTIVE_ADVERBS = {
    "bine": ["joy", "trust"],
    "rău": ["sadness", "anger"],
    "groaznic": ["fear", "sadness"],
    "minunat": ["joy"],
    "oribil": ["fear", "disgust"],
    "îngrozitor": ["fear"],
    "ingrozitor": ["fear"],
    "extraordinar": ["joy", "surprise"],
    "teribil": ["fear", "sadness"],
    "grozav": ["joy"],
    "excelent": ["joy"],
    "fantastic": ["joy"],
    "prost": ["sadness", "anger"],
    "nasol": ["sadness", "anger"],
    "aiurea": ["surprise", "anger"],
}


def build_curated_seed():
    """Build the curated emotion seed dictionary."""
    word_to_emotions = {}

    # Add all adjectives
    for word, emotions in AFFECTIVE_ADJECTIVES.items():
        word_to_emotions[word] = emotions

    # Add all nouns
    for word, emotions in AFFECTIVE_NOUNS.items():
        word_to_emotions[word] = emotions

    # Add all adverbs
    for word, emotions in AFFECTIVE_ADVERBS.items():
        word_to_emotions[word] = emotions

    return {
        "source": "manually_curated",
        "word_to_emotions": word_to_emotions,
        "all_words": sorted(word_to_emotions.keys()),
        "statistics": {
            "total_adjectives": len(AFFECTIVE_ADJECTIVES),
            "total_nouns": len(AFFECTIVE_NOUNS),
            "total_adverbs": len(AFFECTIVE_ADVERBS),
            "total_words": len(word_to_emotions),
        },
        "adjectives": list(AFFECTIVE_ADJECTIVES.keys()),
        "nouns": list(AFFECTIVE_NOUNS.keys()),
        "adverbs": list(AFFECTIVE_ADVERBS.keys()),
    }


def save_curated_seed(output_path):
    """Save the curated seed to JSON."""
    import json

    seed = build_curated_seed()

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(seed, f, ensure_ascii=False, indent=2)

    print(f"Saved curated emotion seed to {output_path}")
    print(f"  Adjectives: {seed['statistics']['total_adjectives']}")
    print(f"  Nouns: {seed['statistics']['total_nouns']}")
    print(f"  Adverbs: {seed['statistics']['total_adverbs']}")
    print(f"  Total: {seed['statistics']['total_words']}")

    return seed


if __name__ == "__main__":
    from pathlib import Path
    output_path = Path(__file__).parent.parent.parent / "data" / "emotion_seed.json"
    save_curated_seed(output_path)
